export const antigonevf = [
  { 'question': `Antigone est sortie le matin tôt pour voir Hémon.`, 'rep': 'Faux' },
  { 'question': `La nourrice est la mère d'Antigone.`, 'rep': 'Faux' },
  { 'question': `Antigone a deux frères et deux sœurs.`, 'rep': 'Faux' },
  { 'question': `Créon est l'oncle paternel d'Antigone.`, 'rep': 'Faux' },
  { 'question': `Créon est l'oncle maternel d'Antigone.`, 'rep': 'Vrai' },
  { 'question': `Créon est le roi de Thèbes.`, 'rep': 'Vrai' },
  { 'question': `Antigone est une jolie jeune fille.`, 'rep': 'Faux' },
  { 'question': `Antigone est aussi belle que sa sœur Ismène.`, 'rep': 'Faux' },
  { 'question': `Les événements de la pièce Antigone se déroulent en une seule journée.`, 'rep': 'Vrai' },
  { 'question': `Antigone mourra à la fin de la pièce.`, 'rep': 'Vrai' },
  { 'question': `Antigone est une petite maigre.`, 'rep': 'Vrai' },
  { 'question': `Antigone est une fille bavarde.`, 'rep': 'Faux' },
  { 'question': `Antigone sera contre toute sa famille.`, 'rep': 'Vrai' },
  { 'question': `Antigone sait dès le début qu'elle va mourir.`, 'rep': 'Vrai' },
  { 'question': `Ismène est bavarde et souriante.`, 'rep': 'Vrai' },
  { 'question': `Hémon est le frère de Créon.`, 'rep': 'Faux' },
  { 'question': `Hémon est le fils de Créon.`, 'rep': 'Vrai' },
  { 'question': `Hémon va mourir à la fin de la pièce.`, 'rep': 'Vrai' },
  { 'question': `Hémon va se suicider en s'enfonçant son épée dans le ventre.`, 'rep': 'Vrai' },
  { 'question': `Hémon se suicide car Antigone est morte.`, 'rep': 'Vrai' },
  { 'question': `Antigone est plus belle que sa sœur Ismène.`, 'rep': 'Faux' },
  { 'question': `Ismène est plus belle qu'Antigone.`, 'rep': 'Vrai' },
  { 'question': `Hémon a choisi Antigone pour être son époux car elle est plus belle qu'Ismène.`, 'rep': 'Faux' },
  { 'question': `Antigone a accepté la demande de mariage de Hémon avec une grand joie.`, 'rep': 'Faux' },
  { 'question': `Créon est fort malgré sa vieillesse.`, 'rep': 'Vrai' },
  { 'question': `Créon est fatigué de son travail de conduire les hommes.`, 'rep': 'Vrai' },
  { 'question': `Quand il était jeune, Créon aimait les livres et la musique.`, 'rep': 'Vrai' },
  { 'question': `Créon est devenu roi après la mort d'Œdipe.`, 'rep': 'Faux' },
  { 'question': `Polynice et Etéocle se sont combattus pour gouverner Thèbes.`, 'rep': 'Vrai' },
  { 'question': `C'est Etéocle qui est devenu roi de Thèbes après la mort d'Œdipe.`, 'rep': 'Vrai' },
  { 'question': `Etéocle refuse de laisser la place à son frère Polynice après un an.`, 'rep': 'Vrai' },
  { 'question': `Polynice est considéré comme traître car il est entré en guerre contre Thèbes aidé des sept princes.`, 'rep': 'Vrai' },
  { 'question': `Etéocle a reçu des funérailles imposantes après sa mort.`, 'rep': 'Vrai' },
  { 'question': `Le cadavre de Polynice est laissé comme proie de corbeaux et des chacals.`, 'rep': 'Vrai' },
  { 'question': `Le cadavre d'Etéocle est laissé comme proie aux corbeaux et aux chacals.`, 'rep': 'Faux' },
  { 'question': `Toute personne qui enterre Polynice sera punie de mort.`, 'rep': 'Vrai' },
  { 'question': `Toute personne qui enterre Polynice sera punie de prison.`, 'rep': 'Faux' },
  { 'question': `C'est le Chœur qui a présenté les personnages.`, 'rep': 'Faux' },
  { 'question': `La première scène d'une pièce de théâtre est appelée scène d'exposition.`, 'rep': 'Vrai' },
  { 'question': `Le prologue est présenté les personnages selon leurs âges.`, 'rep': 'Faux' },
  { 'question': `Une didascalie est une partie d'un dialogue.`, 'rep': 'Faux' },
  { 'question': `Une didascalie est un texte écrit en italique qui donne des informations sur la manière de parler des personnages...`, 'rep': 'Vrai' },
  
  { 'question': `La nourrice croyait qu'Antigone est sortie le matin pour voir un amant.`, 'rep': 'Vrai' },
  { 'question': `Quand Antigone était petite elle ne prenait pas bien soin d'elle comme les autres filles de son âge.`, 'rep': 'Vrai' },
  { 'question': `Antigone, quand elle était petite, elle se maquillait et restait des heures devant la glace.`, 'rep': 'Faux' },
  { 'question': `Au début de la pièce, la nourrice parle d'un amant d'Antigone. Antigone parle de son frère. On appelle cette situation un quiproquo.`, 'rep': 'Vrai' },
  { 'question': `Antigone appelle sa nourrice "Nani".`, 'rep': 'Faux' },
  { 'question': `Antigone appel sa nourrice : "Nounou".`, 'rep': 'Vrai' },
  { 'question': `Antigone a un autre amoureux qu'Hémon.`, 'rep': 'Faux' },
  
  { 'question': `Dès le début de la pièce, Ismène ne sait rien sur le projet d'Antigone.`, 'rep': 'Faux' },
  { 'question': `Ismène ne veut pas enterrer le cadavre de Polynice.`, 'rep': 'Faux' },
  { 'question': `Ismène veut enterrer le cadavre mais elle ne peut pas.`, 'rep': 'Vrai' },
  { 'question': `Ismène est pour le projet d'Antigone mais elle a peur de la mort.`, 'rep': 'Vrai' },
  { 'question': `Antigone a peur de mourir comme sa sœur Ismène.`, 'rep': 'Vrai' },
  { 'question': `Antigone veut enterrer son frère car c'est son devoir`, 'rep': 'Vrai' },
  { 'question': `Créon a interdit l'enterrement de Polynice pour donner l'exemple au peuple de Thèbes.`, 'rep': 'Vrai' },
  { 'question': `Antigone est une fille facile à convaincre.`, 'rep': 'Faux' },
  { 'question': `Le peuple de Thèbes a le même avis que Créon : il faut punir celui qui enterre Polynice.`, 'rep': 'Vrai' },
  { 'question': `Le peuple de Thèbes veut enterrer le cadavre de Polynice.`, 'rep': 'Vrai' },
  { 'question': `Antigone aime la vie, la nature, les animaux ...`, 'rep': 'Vrai' },
  { 'question': `Ismène croit que les femmes doivent croire aux idées et mourir pour elles comme les hommes.`, 'rep': 'Faux' },
  { 'question': `Le cadavre de Polynice est entouré de garde pour le surveiller.`, 'rep': 'Vrai' },
  
  { 'question': `Antigone a une chienne qui s'appelle Rouce.`, 'rep': 'Faux' },
  { 'question': `Antigone demande à sa nourrice de prendre soin de sa chienne et lui annonce son projet.`, 'rep': 'Faux' },
  { 'question': `Antigone demande à la nourrice de tuer sa chienne Douce si elle était trop triste.`, 'rep': 'Vrai' },
  { 'question': `Hémon avoue à Antigone qu'il ne l'aime plus et qu'il voulait Ismène comme sa fiancée le soir du bal`, 'rep': 'Faux' },
  { 'question': `Antigone s'était maquillée et avait porté une belle robe pour donner à Hémon envie d'elle`, 'rep': 'Vrai' },
  { 'question': `Une tirade est une langue réplique`, 'rep': 'Vrai' },
  { 'question': `Antigone annonce à Hémon la date de leur mariage`, 'rep': 'Faux' },
  { 'question': `Hémon était choqué quand Antigone lui annonce qu'elle ne pourra jamais l'épouser`, 'rep': 'Vrai' },
  
  
  
  { 'question': `---Ismène dit à Antigone que Polynice ne l'aimait pas`, 'rep': 'Vrai' },
  
  { 'question': `Les gardes avaient peur d'informer Créon que quelqu'un essaie d'enterrer le cadavre de Polynice`, 'rep': 'Vrai' },
  { 'question': `Les gardes ont tiré au sort pour choisir qui dira à Créon que quelqu'un essaie d'enterrer le cadavre de Polynice`, 'rep': 'Vrai' },
  { 'question': `C'est le garde Jonas qui annonce à Créon la nouvelle de la tentative d'enterrement du cadavre de Polynice`, 'rep': 'Vrai' },
  { 'question': `Les gardes Durand et Jonas avaient le courage d'annoncer à Créon la nouvelle de l'enterrement du cadavre de polynice`, 'rep': 'Faux' },
  { 'question': `Il y avait quatre gardes pour surveiller le cadavre de Polynice`, 'rep': 'Faux' },
  { 'question': `Les trois gardes surveillent le cadavre de Polynice à tour de rôle`, 'rep': 'Vrai' },
  { 'question': `C'était un animal qui a recouvert le cadavre de Polynice et non Antigone`, 'rep': 'Faux' },
  { 'question': `Antigone a recouvert le cadavre de son frère avec une pelle d'enfant`, 'rep': 'Vrai' },
  { 'question': `Au début, Créon accuse l'opposition d'avoir enterrée le cadavre de Polynice`, 'rep': 'Vrai' },
  { 'question': `Créon accuse Antigone dès le début d'être celle qui a essayé de recouvrir le cadavre de Polynice`, 'rep': 'Faux' },
  { 'question': `Créon ordonne Jonas de ne parler à personne de l'affaire de l'enterrement de Polynice`, 'rep': 'Vrai' },
  { 'question': `Le Chœur annonce que la tragédie est comme un ressort bandé et qu'il suffit d'un petit coup de pouce pour que le tragique arrive`, 'rep': 'Vrai' },
  { 'question': `Dans une tragédie on est tranquille car on sait d'avance le sort tragique des personnages`, 'rep': 'Vrai' },
  { 'question': `Dans une tragédie, il n'y a pas d'espoir que le personnage ne meurt pas`, 'rep': 'Vrai' },
  { 'question': `La deuxième fois, Antigone enterre Polynice avec ses propres mains`, 'rep': 'Vrai' },
  { 'question': `La deuxième fois, Antigone enterre Polynice avec un pelle d'enfant`, 'rep': 'Faux' },
  { 'question': `La deuxième tentative d'Antigone de recouvrir le cadavre de son frère est faite en plein jour`, 'rep': 'Vrai' },
  { 'question': `Les trois garde voulaient célébrer la capture d'Antigone en buvant du rouge (vin)`, 'rep': 'Vrai' },
  
  { 'question': `Quand le garde aperçoit Antigone en train d'enterrer son frère, elle se sauve pour ne pas être capturée`, 'rep': 'Faux' },
  { 'question': `Antigone avoue à Créon que c'était elle qui tenté de recouvrir le cadavre de Polynice les deux fois`, 'rep': 'Vrai' },
  { 'question': `La pelle qu'a utilisé Antigone pour enterrer son frère était la pelle de Polynice`, 'rep': 'Vrai' },
  
  { 'question': `Créon voulait sauver Antigone en faisant disparaître les gardes`, 'rep': 'Vrai' },
  { 'question': `Antigone accepte la proposition de Créon (faire disparaître les trois gardes)`, 'rep': 'Faux' },
  { 'question': `Selon Antigone, les personnes qu'on enterrent pas errent éternellement sans jamais trouver de repos`, 'rep': 'Vrai' },
  { 'question': `Antigone ne pardonne pas à son frère d'être traître et révolté`, 'rep': 'Faux' },
  { 'question': `Antigone ne savait pas que Créon a interdit l'enterrement de Polynice`, 'rep': 'Faux' },
  { 'question': `Selon Créon, la loi doit être appliquée aux princes avant le peuple`, 'rep': 'Vrai' },
  { 'question': `Créon était obligé de faire mourir Antigone car le peuple de Thèbes sait qu'elle a bravé la loi`, 'rep': 'Vrai' },
  { 'question': `Créon explique à Antigone qu'il est important un enterrement selon les règles`, 'rep': 'Faux' },
  { 'question': `Antigone reconnait qu'un enterrement selon les règles est une absurdité. C'est pour cela qu'elle décide de ne pas l'enterrer`, 'rep': 'Faux' },
  { 'question': `Antigone demande à Créon d'être clément et de la pardonner`, 'rep': 'Faux' },
  { 'question': `Antigone dit à Créon qu'il ne peut pas la sauver et qu'il peut seulement la faire mourir`, 'rep': 'Vrai' },
  { 'question': `Créon avoue à Antigone que l'interdiction de l'enterrement de Polynice est une affaire politique et qu'il aurait aimé enterrer le cadavre`, 'rep': 'Vrai' },
  { 'question': `Créon reconnait que l'interdiction de l'enterrement de Polynice est ignoble, mais il le fait tout de même pour Thèbes`, 'rep': 'Vrai' },
  { 'question': `Créon aurait aimé ne pas être roi`, 'rep': 'Vrai' },
  { 'question': `Antigone reproche à Créon le fait dire oui (accepter d'être roi de Thèbes, de faire des choses qu'il n'aime pas)`, 'rep': 'Vrai' },
  { 'question': `Antigone se sent plus forte que Créon car lui, il a accepté d'être roi de Thèbes alors qu'elle a dit 'non' à sa loi qui interdit l'enterrement de Polynice`, 'rep': 'Vrai' },
  { 'question': `Antigone croit que Créon n'a pas de pouvoir même s'il est roi`, 'rep': 'Vrai' },
  { 'question': `Créon pense que la politique demande beaucoup de sacrifice pour sauver le royaume`, 'rep': 'Vrai' },
  { 'question': `Créon a le choix de ne pas tuer Antigone`, 'rep': 'Faux' },
  { 'question': `Créon est obligé d'appliquer la loi et tuer Antigone`, 'rep': 'Vrai' },
  { 'question': `Créon voit que sauver Thèbes est plus important que sauver Antigone`, 'rep': 'Vrai' },
  { 'question': `---Créon était une brute et un tyran`, 'rep': 'Vrai' },
  { 'question': `Créon aime faire la politique avec intelligence et non avec la force`, 'rep': 'Vrai' },
  { 'question': `Pour Créon, il faut dire 'Non' si on nous oblige à faire des choses contre nos croyances`, 'rep': 'Faux' },
  { 'question': `'Oui' selon Créon signifie accepter de faire des choses qu'on aime pas pour le bien de l'Etat`, 'rep': 'Vrai' },
  { 'question': `Créon sait bien qu'il joue le bon rôle: tuer Antigone`, 'rep': 'Faux' },
  { 'question': `Quand Antigone était petite Polynice lui offre une fleur de papier`, 'rep': 'Vrai' },
  { 'question': `Avant d'aller enterrer le cadavre de Polynice, Antigone a longtemps regardé la fleur que son frère lui a offert pour avoir du courage`, 'rep': 'Vrai' },
  { 'question': `Polynice a déjà donné à son père Œdipe un coup de poing`, 'rep': 'Vrai' },
  { 'question': `Etéocle engageait des tueurs pour tuer son père Œdipe`, 'rep': 'Vrai' },
  { 'question': `Etéocle était loyal envers Thèbes`, 'rep': 'Faux' },
  { 'question': `Etéocle que tout Thèbes croit bon et loyal était en réalité aussi traître que Polynice`, 'rep': 'Vrai' },
  { 'question': `Etéocle est considéré par Thèbes comme un héros`, 'rep': 'Vrai' },
  { 'question': `Dans la guerre contre Thèbes, Polynice a tué Etéocle et Créon a tué Polynice`, 'rep': 'Faux' },
  { 'question': `Après la guerre, les corps de Polynice et Etéocle étaient méconnaissables`, 'rep': 'Vrai' },
  { 'question': `Créon a pu identifier les cadavres de Polynice et Etéocle de leurs visages`, 'rep': 'Faux' },
  { 'question': `Créon était dans sa jeunesse aussi têtu qu'Antigone`, 'rep': 'Vrai' },
  { 'question': `Même en sachant que ses deux frères étaient traîtres, Antigone n'a pas renoncé à son projet`, 'rep': 'Vrai' },
  { 'question': `Antigone a accepté l'idée de bonheur que lui propose Créon`, 'rep': 'Faux' },
  { 'question': `Antigone était sur le point de de renoncer à son projet. Mais le mot 'bonheur' lui fait changer d'avis`, 'rep': 'Vrai' },
  { 'question': `Si Hémon dit 'oui' comme son père, Antigone ne l'aimera plus`, 'rep': 'Vrai' },
  { 'question': `Antigone et Créon avait la même idée sur le bonheur`, 'rep': 'Faux' },
  { 'question': `Antigone compare Créon avec son idée sur la vie à un chien qui lèche un os`, 'rep': 'Vrai' },
  { 'question': `Antigone insulte Créon de cuisinier car il était cuisinier à sa jeunesse`, 'rep': 'Faux' },
  { 'question': `Après la capture d'Antigone, Ismène se joint à elle dans son projet`, 'rep': 'Faux' },
  { 'question': `Antigone n'a pas voulu qu'Ismène meurt aussi car elle a changé son avis tard`, 'rep': 'Vrai' },
  { 'question': `Après sa longue discussion avec Antigone, Créon comprend qu'elle n'est pas faite pour mourir`, 'rep': 'Faux' },
  { 'question': `Les habitants de Thèbes ne veulent pas la mort d'Antigone`, 'rep': 'Faux' },
  { 'question': `Créon était obligé de tuer Antigone car la foule est au courant de sa transgression de la loi`, 'rep': 'Vrai' },
  { 'question': `Hémon déclare à son père qu'il se mariera à Ismène après la mort d'Antigone`, 'rep': 'Faux' },
  
  { 'question': `Antigone seule avec le garde, ils parlent au début de son amour pour Hémon`, 'rep': 'Faux' },
  { 'question': `Le garde informe Antigone qu'elle sera pendue`, 'rep': 'Faux' },
  { 'question': `On a enterré Antigone vivante car on ne voulait pas souiller la ville de son sang`, 'rep': 'Vrai' },
  { 'question': `Antigone demande au garde de donner son anneau à Hémon après sa mort`, 'rep': 'Faux' },
  { 'question': `Antigone donne au garde une bague pour lui écrire une lettre à Hémon`, 'rep': 'Vrai' },
  { 'question': `Dans sa lettre d'adieu, Antigone voulait qu'Hémon sache qu'elle avait peur de la mort`, 'rep': 'Vrai' },
  { 'question': `C'est le Chœur qui a annoncé la mort d'Antigone et Hémon`, 'rep': 'Faux' },
  { 'question': `Au moment où on enterrait Antigone vivante, elle commence à se plaindre et à crier`, 'rep': 'Faux' },
  { 'question': `Créon dégage lui-même les pierres pour ouvrir la tombe d'Antigone`, 'rep': 'Vrai' },
  { 'question': `Antigone s'est suicidée en se tranchant la gorge`, 'rep': 'Faux' },
  { 'question': `Dans la tombe où Antigone est morte, Créon crache sur le visage de son fils Hémon`, 'rep': 'Faux' },
  { 'question': `Dans le trou où Antigone a été enterrée, Hémon tire son épée pour tuer son père`, 'rep': 'Vrai' },
  { 'question': `Après la mort d'Antigone, Hémon sort du trou accompagné de son père Créon`, 'rep': 'Faux' },
  { 'question': `Eurydice s'est coupée la gorge après la mort de son fils`, 'rep': 'Vrai' },
  { 'question': `Après la mort de sa nièce, son fils et sa femme, Créon décide de ne plus être roi`, 'rep': 'Faux' },
  { 'question': `Après la mort d'Antigone, d'Hémon et d'Eurydice, les gardes jouaient une partie de cartes comme d'habitude.`, 'rep': 'Vrai' },
  { 'question': `La pièce Antigone est composée de trois actes`, 'rep': 'Faux' }
]