
module.exports = { ordreEventsData }; const ordreEventsData=[
  `Un prisonnier souffre depuis cinq semaines d'une seule idée : "Condamné à mort"`,
  `Le condamné se rappelle son procès et sa réaction le moment du verdict`,
  `Le condamné essaie d'accepter sa sentence : On va tous mourir un jour ou un autre`,
  `Le condamné est transféré à Bicêtre`,
  `Le condamné a eu une plume et du papier pour écrire`,
  `Le condamné décide d'écrire pour oublier sa souffrance`,
  `Le condamné s'interroge sur l'utilité d'écrire pour sauver les autres s'il sera mort`,
  `Le condamné compte le temps qui lui reste pour vivre`,
  `Le condamné fait son testament et pense à sa famille et surtout sa fille`,
  `Description d'une cellule da Bicêtre`,
  `Lecture des écritures sur les murs du cachots laissées par les anciens condamnés à mort`,
  `Le condamné lit les noms des criminels qui sont passés par cette cellule`,
  `Le condamné décrit l'horrible scène du ferrage des forçats. Il s'évanouit juste apès`,
  `De l'infirmerie, il regarde les forças partir : il préfère la mort aux travaux forcés`,
  `Après le petit moment de liberté dans l'infirmerie, le condamné est dans sa cellule; il pense à s'évader`,
  `Le condamné se souvient de la jeunne fille qui chantait da sa voix douce`,
  `Encore dans son idée d'évasion, le condamné s'imagine dans le port mais un gendarme met fin à son rêve`,
  `6h du matin, le guichetier était gentil. Sa gentillesse perturbe le condamné. Il doute que c'est son jour d'exécution`,
  `Le directeur de la prison rend visite au condamné. Celui-ci est sûr que c'est pour ce jour-là`,
  `Le narrateur voit la mort partout: dans le geôlier, les murs, les portes..`,
  `Le narrateur reçoit deux visites : un prêtre et l'huissier qui lui informe du rejet de son pourvoi en cassation et que son exécution serait le même jours à la place de Grève`,
  `7h30 du matin, Le condamné est transféré à la Concièrgerie accompagné de l'huissier et du prêtre`,
  `L'huissier remet le condamné au directeur. Le condamné rencontre le frioche qui lui raconte son histoire et lui prend son redingote.`,
  `Le condamné est en colère à cause du frioche qui lui a pris sa redingote`,
  `Les condamné est dans une cellule à la Concièrgerie. On lui donne tout ce qu'il lui faut pour écrire.`,
  `10h, Le narrateur pense à sa fille qui restera sans père, rejetée par la société à cause de son père`,
  `Le condamné se demande comment on meurt sur l'échafaud. Il n'ose pas nommer la guillotine`,
  `Le condamné se rappelle avoir déjà vu monter une guillotine`,
  `Le condamné à mort pense à la grâce et il souhaite les travaux forcés à la mort`,
  `Le condamné reçoit la visite d'un prêtre qui parle beaucoup mais qui ne touche pas le condamné`,
  `Un homme entre dans la cellule du condamné et prend ses mesures : on va rénover la Conciérgerie`,
  `Un gendarme prend sa garde, il demande au condamné de revenir après sa mort pour lui révéler les numéro de lotterie.`,
  `Le narrateur se souvient de son enfance. Il pense à Pepa, une jeune fille qu'il aimait`,
  `En se souvenant de son enfance et de Pepa, le condamné pense à son crime`,
  `Description brève de l'Hôtel de Ville`,
  `12:45, Le condamné ressent une violente douleur partout dans son corps. il lui reste 2h et 45min à vivre`,
  `Le narrateur répond les gens qui disent que la guillotine n'est pas douloureuse`,
  `Le condamné pense sans arrêt au roi : sa signature peut lui sauver la vie`,
  `Le condamné imagine se qu'il verra après la mort. Il demande un prête et un crucifix`,
  `Le condamné dort; c'est son dernier sommeil. Il fait un cauchemar`,
  `Marie rend visite à son père. Elle ne le reconnait pas, pire: elle le croit mort : Le condamné perd tout espoir`,
  `1 heure avant sa mort: le condamné essaie de se montrer plus fort`,
  `Le condamné pense aux gens qui assisterons à son exécution`,
  `Le prisonnier pense toujours à sa fille et se demande s'il aurait plus de temps pour écire quelques pages pour elle`,
  `A l'Hôtel de Ville, à 3h. Le bourreau et deux valets prépare le condamné pour être guillotiné`,
  `Le condamné demande au juge d'attendre 5min, 1min. Il a toujours l'espoir d'une grâce du dernier moment. 4h sonne`,
  ]