module.exports = { phrases }; const phrases=[`Le condamné avait six semaines à vivre`,
`Le condamné a commis un crime de sang`,
`Le dernier jour d'un condamné est un roman à thèse`,
`Victor Hugo a écrit Le dernier jour d'un condamné en 1829`,
`Victor Hugo était contre la peine de mort`,
`Le condamné avait une fille qui s'appelle Marie`,
`Le narrateur décrit sa cellule à Bicêtre`,
`Le condamné écrit son journal intime`,
`Le journal intime du condamné lui permet de moins souffrir`,
`Le frioche a pris la redingote du condamné`,
`Le condamné adresse son journal aux juges`,
`Victor Hugo voulait abolir la peine de mort`,
`Le condamné s'inquiète plus pour sa fille`,
`Le condamné est issu d'une famille bourgeoise`,
`Le condamné assiste au spectacle du ferrage des forçats`,
`Le condamné compte les jours qui lui reste`,
`Les mûrs du cachot étaient pleins de transcriptions`,
`Le condamné rêve de s'évader du prison`,
`Le directeur de la prison rend visite au condamné`,
`Le condamné reçoit la visite du prêtre`,
`La gentillesse du directeur a fait peur au condamné`,
`Le narrateur voit la mort partout dans sa cellule`,
`L'huissier annonce au condamné que son pourvoi est rejeté`,
`Le condamné est exécuté à la place de Grève`,
`Le prisonnier est transféré à la Conciérgerie`,
`La fille du condamné restera sans père`,
`Les gens croient que la guillotine ne fait pas souffrir`,
`Le condamné avait l'espoir d'une grâce du roi`,
`Le prêtre récite machinalement ses prières`,
`Le condamné préfère cent fois la mort aux travaux forcés à perpetuité`,
`Le condamné se rappelle de ses souvenirs d'enfance avec Pepa`,
`La vie du condamné dépond d'un signature du roi`,
`La petite Marie ne reconnait pas son papa`
]