module.exports = { djcvf }; const djcvf = [{'question' : `Victor Hugo est un écrivain du 20ème siècle`, 'rep': 'Faux'}, 
{'question' : `Victor Hugo est un écrivain du 19ème siècle`, 'rep': 'Vrai'},
{'question' : `Le dernier jour d'un condamné est paru en 1929`, 'rep': 'Faux'},
{'question' : `Le dernier jour d'un condamné est paru en 1829`, 'rep': 'Vrai'},
{'question' : `Le dernier jour d'un condamné est un roman autobiographique`, 'rep': 'Faux'},
{'question' : `Le dernier jour d'un condamné est un journal intime`, 'rep': 'Faux'},
{'question' : `Le dernier jour d'un condamné est un roman à thèse`, 'rep': 'Vrai'},
{'question' : `Le narrateur dans le dernier jour d'un condamné est un condamné à mort`, 'rep': 'Vrai'},
{'question' : `Le narrateur dans le dernier jour d'un condamné est Victor Hugo`, 'rep': 'Faux'},
{'question' : `Le dernier jour d'un condamné est contre la peine de mort.`, 'rep': 'Faux'},
{'question' : `La thèse défendue dans Le dernier jour d'un condamné est l'abolition de la peine de mort`, 'rep': 'Faux'},
{'question' : `Le condamné du roman est condamné aux travaux forcés.`, 'rep': 'Faux'},
{'question' : `Le condamné est mis d'abord à Bicêtre`, 'rep': 'Faux'},
{'question' : `Le condamné est père de deux filles`, 'rep': 'Faux'},
{'question' : `Le condamné est père d'une fille de trois ans`, 'rep': 'Vrai'},
{'question' : `Le condamné a fait un crime de sang`, 'rep': 'Vrai'},
{'question' : `Le condamné est en prison car il a volé une banque`, 'rep': 'Faux'},
{'question' : `Le condamné est exécuté à Bicêtre`, 'rep': 'Faux'},
{'question' : `Le condamné est exécuté à la place de Grève`, 'rep': 'Faux'},
{'question' : `Le condamné est resté cinq semaines en prison avant son exécution`, 'rep': 'Faux'},
{'question' : `Le condamné est resté six semaine en prison avant son exécution`, 'rep': 'Vrai'},
{'question' : `Dans le chapitre 32, le condamné annonce qu'il lui reste un jour à vivre`, 'rep': 'Faux'},
{'question' : `Dans le chapitre 18, le condamné annonce qu'il lui reste un jour à vivre`, 'rep': 'Vrai'},
{'question' : `Les prisonniers étaient indifférents face à la souffrance du condamné ?`, 'rep': 'Vrai'},
{'question' : `Les prisonniers étaient empathiques avec le condamné ?`, 'rep': 'Faux'},
{'question' : `Le récit du condamné est raconté avec la focalisation interne`, 'rep': 'Faux'},
{'question' : `Le condamné écrit son journal pour le vendre et laisser l'argent à sa fille.`, 'rep': 'Faux'},
{'question' : `Le condamné écrit son journal pour donner une leçon aux juges.`, 'rep': 'Vrai'},
{'question' : `Le condamné se met à écrire son journal pour moins souffrir.`, 'rep': 'Vrai'},
{'question' : `L'écriture pour le condamné était une manière d'exprimer sa souffrance`, 'rep': 'Vrai'},
{'question' : `Le condamné est issu d'une famille pauvre`, 'rep': 'Faux'},
{'question' : `Le condamné est d'une famille bourgeoise.`, 'rep': 'Vrai'},
{'question' : `Le procès du condamné est ouvert en mois d'août`, 'rep': 'Vrai'},
{'question' : `Le jury est composé de dix personnes`, 'rep': 'Faux'},
{'question' : `L'avocat informe que l'absence de préméditation sera au service du condamné`, 'rep': 'Vrai'},
{'question' : `L'avocat a l'espoir que le condamné sera jugé aux travaux forcés à perpétuité.`, 'rep': 'Vrai'},
{'question' : `L'avocat a l'espoir que le condamné sera jugé de 20 ans de prison.`, 'rep': 'Faux'},
{'question' : `Dans les prisons les prisonniers parlent un langage appelé 'argot'`, 'rep': 'Vrai'},
{'question' : `D'après le condamné, les pourvois en cassation sont souvent acceptés`, 'rep': 'Faux'},
{'question' : `D'après le condamné, les pourvois en cassation sont souvent rejetés (refusés)`, 'rep': 'Vrai'},
{'question' : `Le narrateur avait 40 ans`, 'rep': 'Vrai'},
{'question' : `Le condamné est âgé de 30 ans`, 'rep': 'Faux'},
{'question' : `Le condamné a apprécié le ferrage des forçats`, 'rep': 'Faux'},
{'question' : `Le condamné s'est évanoui après le spectacle du ferrage des forçats.`, 'rep': 'Vrai'},
{'question' : `Les prisonniers ferrés seront conduits au bagne de l'Hôtel de ville`, 'rep': 'Faux'},
{'question' : `Après le spectacle du ferrage des forçats, le condamné croit que le bagne est meilleur que la guillotine.`, 'rep': 'Faux'},
{'question' : `Après le spectacle du ferrage des forçats, le condamné croit que la guillotine est meilleur que le bagne`, 'rep': 'Vrai'},
{'question' : `L'huissier annonce au condamné que le procureur général a rejeté son pourvoi en cassation`, 'rep': 'Vrai'},
{'question' : `L'huissier informe le condamné que le procureur général a accepté son pourvoi en cassation`, 'rep': 'Faux'},
{'question' : `Le frioche a pris la redingote du condamné lui a donné une veste`, 'rep': 'Vrai'},
{'question' : `Le frioche a pris la veste du condamné en échange d'une redingote`, 'rep': 'Faux'},
{'question' : `Le condamné n'a pas pu prononcer le mot guillotine.`, 'rep': 'Faux'},
{'question' : `La guillotine est inventée par un forgeron`, 'rep': 'Faux'},
{'question' : `C'était un médecin qui a inventé La guillotine`, 'rep': 'Vrai'},
{'question' : `C'est le juge qui peut donner la grâce au condamné.`, 'rep': 'Faux'},
{'question' : `Le condamné avait un espoir d'avoir la grâce du roi`, 'rep': 'Vrai'},
{'question' : `Marie était le nom de l'amour d'enfance du condamné`, 'rep': 'Faux'},
{'question' : `L'amour d'enfance du condamné s'appellait Pepa`, 'rep': 'Faux'},
{'question' : `Les gens croient que la guillotine est très douloureuse.`, 'rep': 'Faux'},
{'question' : `Pour les gens, la guillotine est une fin douce et ne fait pas souffrir`, 'rep': 'Vrai'},
{'question' : `Le condamné donne le nom de 'valet de la guillotine" au bourreau`, 'rep': 'Vrai'},
{'question' : `Le condamné considère le bourreau comme son sauveur.`, 'rep': 'Faux'}
]

 /* 
 export const vfData = [
  {'question': 'Sidi Mohammed était un enfant heureux', 'rep': 'Faux'},
  {'question': 'Les événements du roman se déroulent à Fès.', 'rep': 'Vrai'},
  {'question': 'Lalla Aicha était l\'amie intime et la confidente de Lalla Zoubida.', 'rep': 'Vrai'},
  {'question': 'Maâlem Abdeslam était un homme sévère et méchant', 'rep': 'Faux'},
  {'question': `Le père du narrateur est un homme pieux et peu bavard`, 'rep': 'Vrai'},
  {'question': `Sidi Mohammed aimait le bain maure`, 'rep': 'Faux'},
  {'question': `Sidi Mohammed n'aimait pas le fqih`, 'rep': 'Vrai'},
  {'question': `<i>Le Chapelet d'ombre</i> est un roman de Ahmed Sefrioui`, 'rep': 'Vrai'},
  {'question': `<i>Le voyageur sans bagage</i> est un roman de Ahmed Sefrioui`, 'rep': 'Faux'},
  {'question': `<i>La boîte à merveilles</i> est un roman marocain d'expression française`, 'rep': 'Vrai'},
  {'question': `Ahmed SEFRIOUI est un écrivain du 19ème siècle.`, 'rep': 'Faux'},
  {'question': `La Boîte à merveilles est une autobiographique.`, 'rep': 'Faux'},
  {'question': `Abdellah l'épicier raconte des histoires merveilleuses. `, 'rep': 'Vrai'},
  {'question': `Avant Achoura, le fqih est devenu aimable`, 'rep': 'Vrai'},
  {'question': `Quand les élèves nettoyaient le msid, Sidi Mohammed apportait de l'eau de la fontaine`, 'rep': 'Faux'},
  {'question': `Sidi El Arafi était un sanctuaire que les femmes visitaient le jeudi`, 'rep': 'Faux'},
  {'question': `Sidi Mohammed aimait Sidi El Arafi`, 'rep': 'Vrai'},
  {'question': `Avant Achoura, Sidi Mohammed accompagne sa mère à la kissaria pour acheter des jouets`, 'rep': 'Faux'},
  {'question': `Moulay Larbi a perdu son atelier à cause de Maâlem Abdeslam`, 'rep': 'Faux'},
  {'question': `Lalla Aïcha a vendu ses bijoux pour aider son mari Moulay Larbi`, 'rep': 'Vrai'},
  {'question': 'Le narrateur est le personnage principal', 'rep':'Vrai'},
  {'question': 'Le fqih était un homme doux et clément.', 'rep':'Faux'},
  {'question': 'Le Msid est un espace de joie pour le narrateur.', 'rep':'Faux'},
  {'question': 'Sidi Mohammed avait un petit frère', 'rep':'Faux'},
  {'question': 'La chouafa était la tante de Sidi Mohammed', 'rep':'Faux'},
  {'question': 'Maâllem Abdeslam était babouchier', 'rep':'Faux'},
  {'question': 'Lalla Zoubida était une femme bavarde', 'rep':'Vrai'},
  {'question': 'Le narrateur avait six ans', 'rep':'Vrai'},
  {'question': '<i> La Boîte à merveilles</i> est une œuvre écrite en 1952.', 'rep':'Vrai'},
  {'question': '<i>La Boîte à merveilles</i> est publié en 1952', 'rep':'Faux'},
  {'question': '<i>La boite à merveilles</i> est une nouvelle réaliste.', 'rep':'Faux'},
  {'question': 'Sidi Mohammed apprécie Zineb.', 'rep':'Faux'},
  {'question': '<i>La Boîte à merveilles</i> contenait des objets hétéroclites et ordinaires.', 'rep':'Vrai'},
  {'question': 'Lalla Zoubida et Rahma se réconcilient le jour de la disparition de Zineb.', 'rep':'Vrai'},
  {'question': 'Lalla Zoubida s\'est disputée avec Rahma à cause des enfants.', 'rep':'Faux'},
  {'question': 'Grace à son imagination, Sidi Mohammed se sent différent des enfants de son âge.', 'rep':'Vrai'},
  {'question': 'Lalla Zoubida est une femme discrète (timide).', 'rep':'Faux'},
  {'question': 'Sidi Mohammed considère les objets de sa Boîte comme ses seuls amis.', 'rep':'Vrai'}]
  */