export const vfData = [
  {'question': 'Sidi Mohammed était un enfant heureux', 'rep': 'Faux'},
  {'question': 'Les événements du roman se déroulent à Fès.', 'rep': 'Vrai'},
  {'question': 'Lalla Aicha était l\'amie intime et la confidente de Lalla Zoubida.', 'rep': 'Vrai'},
  {'question': 'Maâlem Abdeslam était un homme sévère et méchant', 'rep': 'Faux'},
  {'question': `Le père du narrateur est un homme pieux et peu bavard`, 'rep': 'Vrai'},
  {'question': `Sidi Mohammed aimait le bain maure`, 'rep': 'Faux'},
  {'question': `Sidi Mohammed n'aimait pas le fqih`, 'rep': 'Vrai'},
  {'question': `<i>Le Chapelet d'ombre</i> est un roman de Ahmed Sefrioui`, 'rep': 'Vrai'},
  {'question': `<i>Le voyageur sans bagage</i> est un roman de Ahmed Sefrioui`, 'rep': 'Faux'},
  {'question': `<i>La boîte à merveilles</i> est un roman marocain d'expression française`, 'rep': 'Vrai'},
  {'question': `Ahmed SEFRIOUI est un écrivain du 19ème siècle.`, 'rep': 'Faux'},
  {'question': `La Boîte à merveilles est une autobiographique.`, 'rep': 'Faux'},
  {'question': `Abdellah l'épicier raconte des histoires merveilleuses. `, 'rep': 'Vrai'},
  {'question': `Avant Achoura, le fqih est devenu aimable`, 'rep': 'Vrai'},
  {'question': `Quand les élèves nettoyaient le msid, Sidi Mohammed apportait de l'eau de la fontaine`, 'rep': 'Faux'},
  {'question': `Sidi El Arafi était un sanctuaire que les femmes visitaient le jeudi`, 'rep': 'Faux'},
  {'question': `Sidi Mohammed aimait Sidi El Arafi`, 'rep': 'Vrai'},
  {'question': `Avant Achoura, Sidi Mohammed accompagne sa mère à la kissaria pour acheter des jouets`, 'rep': 'Faux'},
  {'question': `Moulay Larbi a perdu son atelier à cause de Maâlem Abdeslam`, 'rep': 'Faux'},
  {'question': `Lalla Aïcha a vendu ses bijoux pour aider son mari Moulay Larbi`, 'rep': 'Vrai'},
  {'question': 'Le narrateur est le personnage principal', 'rep':'Vrai'},
  {'question': 'Le fqih était un homme doux et clément.', 'rep':'Faux'},
  {'question': 'Le Msid est un espace de joie pour le narrateur.', 'rep':'Faux'},
  {'question': 'Sidi Mohammed avait un petit frère', 'rep':'Faux'},
  {'question': 'La chouafa était la tante de Sidi Mohammed', 'rep':'Faux'},
  {'question': 'Maâllem Abdeslam était babouchier', 'rep':'Faux'},
  {'question': 'Lalla Zoubida était une femme bavarde', 'rep':'Vrai'},
  {'question': 'Le narrateur avait six ans', 'rep':'Vrai'},
  {'question': '<i> La Boîte à merveilles</i> est une œuvre écrite en 1952.', 'rep':'Vrai'},
  {'question': '<i>La Boîte à merveilles</i> est publié en 1952', 'rep':'Faux'},
  {'question': '<i>La boite à merveilles</i> est une nouvelle réaliste.', 'rep':'Faux'},
  {'question': 'Sidi Mohammed apprécie Zineb.', 'rep':'Faux'},
  {'question': '<i>La Boîte à merveilles</i> contenait des objets hétéroclites et ordinaires.', 'rep':'Vrai'},
  {'question': 'Lalla Zoubida et Rahma se réconcilient le jour de la disparition de Zineb.', 'rep':'Vrai'},
  {'question': 'Lalla Zoubida s\'est disputée avec Rahma à cause des enfants.', 'rep':'Faux'},
  {'question': 'Grace à son imagination, Sidi Mohammed se sent différent des enfants de son âge.', 'rep':'Vrai'},
  {'question': 'Lalla Zoubida est une femme discrète (timide).', 'rep':'Faux'},
  {'question': 'Sidi Mohammed considère les objets de sa Boîte comme ses seuls amis.', 'rep':'Vrai'}]