module.exports = { phrases }; const phrases=[
`Antigone sait qu'elle va mourir`,
`Antgone veut enterrer Polynice car c'est son devoir`,
`Antigone est la fille d'Oedipe`,
`Antigone mourra à la fin de la pièce`,
`Hémon supplie son père de sauver Antigone`,
`Ismène avait peur de mourir`,
`Le messager annonce la mort d'Antigone`,
`Hémon est mort suicidé`,
`Antigone est une tragédie moderne`,
`Les trois gardes ont capturé Antigone entrain d'enterrer son frère`,
`Antigone n'a pas nié son acte`,
`Créon informe Antigone que ses deux frères étaient traîtres`,
`Le Prologue commence par la présentation des personnages`,
`Antigone a laissé à Hémon une lettre d'adieu`,
`Le garde était indifférent à la peur d'Antigone`,
`Créon veut sauver Antigone`,
`Antigone a bravé la loi de Créon`,
`Créon veut donner l'exemple au peuble de Thèbes`,
`Ismène essaie de dissuader Antigone`,
`Antigone utilise une pelle pour enterrer son frère`,
`Antigone demande à la nourrice de prendre soin de Douce`,
`La nourrice soupçonne Antigone d'avoir un amoureux`,
`Antigone fait sees adieux à Hémon`,
`Ismène veut enterrer son frère mais elle ne peut pas`,
`Antigone dit à Hémon qu'elle ne sera jamais son épouse`,
`Les gardes parlent de la prime qu'ils vont toucher`,
`Le choeur demande à Créon de sauver Antigone`,
]