module.exports = { ordreEventsData }; const ordreEventsData=[
  `Le prologue présente les personnages.`,
  `Le prologue raconte l'histoire des deux frères d'Antigone.`,
  `La nourrice surprend Antigone qui est sortie très tôt le matin.`,
  `Ismène essaie de convaince Antigone de ne pas enterrer le codavre de Polynice.`,
  `Antigone rejette tous les arguments de sa soeur Ismène.`,
  `Antigone demande à sa nourrice de prendre soin de sa chienne.`,
  `Antigone fait ses adieux à Hémon.`,
  `Ismène essaie une deuxième fois de convaincre Antigone. Cette dernière lui dit que c'est trop tard.`,
  `Le garde informe Créon que quelqu'un a essayé d'enterrer le cadavre de Polynice.`,
  `Le Choeur définit la tragédie et sa différence avec le drame.`,
  `Les gardes capture Antigone entrain de couvrir le cadavre de Polynice.`,
  `Les gardes discutent de la prime qu'ils toucheront.`,
  `Créon voulait sauver Antigone en faisant disparaitre les gardes.`,
  `Créon révèle à Antigone des secrets sur ses deux frères.`,
  `Créon conseille Antigone de se marier et vivre son bonheur.`,
  `Ismène décide enfin de mourir comme Antigone.`,
  `Créon ordonne les gardes d'emmener Antigone.`,
  `Le Choeur demande à Créon de sauver Antigone.`,
  `Hémon supplie son père de sauver Antigone.`,
  `Le garde informe Créon que les habitants envahissent e palais.`,
  `Seule avec la garde, Antigone parle de sa peur alors que le garde parle de son statut.`,
  `Antigone demande au garde d'écrire une lettre à Hémon.`,
  `Le Messager annonce la mort d'Antigone et d'Hémon.`,
  `Le Choeur annonce la mort d'Eurydice.`,
  `Après la mort de sa femme et de son fils, Créon doit continuer son travail.`,
  `Les gardes continuent leur jeu de cartes.`
]